
GET http://localhost:8080/endpoints HTTP/1.1

###

GET http://localhost:8080/invariants?type=any HTTP/1.1

###

GET http://localhost:8080/invariants?type=booleans HTTP/1.1

###

POST http://localhost:8080/phoeglang HTTP/1.1
Content-Type: application/json

{
    "query": "\"av_col\" + 5"
}

###

POST http://localhost:8080/phoeglang HTTP/1.1
Content-Type: application/json

{
    "query": "MAX(7,6-5) < 5 AND MIN(av_col,4-2) > 7"
}

###

POST http://localhost:8080/phoeglang HTTP/1.1
Content-Type: application/json

{
        "query": "'num_col' > MIN('av_col' - 2)"
}

###

POST http://localhost:8080/graphs/points?order=3&x_invariant=av_col&y_invariant=num_col&colour=num_vertices HTTP/1.1
Content-Type: application/json

{
    "query": "'num_col' >= (MIN('av_col')) + 2"
}

###


GET http://localhost:8080/phoeglang HTTP/1.1



###

# This is broken
GET http://localhost:8080/graphs/points?order=7&x_invariant=av_col&y_invariant=num_edges&colour=num_vertices&constraints%5B0%5D%5Bname%5D=is_connected&constraints%5B0%5D%5Bminimum_bound%5D=0&constraints%5B0%5D%5Bmaximum_bound%5D=0


###

GET http://localhost:8080/graphs/polytope?order=7&x_invariant=max_huv&y_invariant=max_deg&constraints[0][name]=is_connected&constraints[0][minimum_bound]=1&constraints[0][maximum_bound]=1